apiVersion: v1
kind: Pod
metadata:
  name: guaranteed
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80  
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 200m
          memory: 200Mi   
